"""initial

Revision ID: 87f252b93c89
Revises:
Create Date: 2026-06-24 20:43:49.083693

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "87f252b93c89"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
